= Cheryl Toh - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: HackEat

---

== Overview
HackEat was morphed from AddressBook - Level 4, a desktop application which is used
for teaching Software Engineering Principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX.
It is written in Java, and has about 10 kLoC.

_Start of Extract [from: Read Me] written by Jackson Huang_

HackEat is a next-gen food recommendation and ordering app for the hackers, the programmers, the creators of world bustling and bursting with world-changing ideas but running short on time ⏰⏳.
Perfect for the busy software developer or desk hermit: Use CLI commands to accelerate the chore of finding the right food.
HackEat takes the stress, thinking and time-waste out of deciding what to eat. Order your food in style with commands like `order` to stay in the zone even when you’re not programming.

_End of Extract [from: Read Me] written by Jackson Huang_

== Summary of contributions

* *Major enhancement*: Provide users with a personalised and customised experience

** What it does: Allows users to view and modify their details as well as update their profile picture

** Justification: This feature allows users to update their contact details and allergies - both of which are imperative to HackEat.
Since the `order` command utilises the allergies of users to determine the types of food that they can eat, it is essential
to have an `edituser` command that allows users to easily update their allergies. In addition, this feature also makes it simple for users to change
their contact details, which can prove to be useful if they want their food to be delivered to the right place. Lastly, with the prevalence
of user customisation these days, what users appreciate is an emotionally tangible link between them and the app. Having a profile picture is
the first step to achieving this.

** Highlights: This enhancement resulted in the implementation of two new commands - `changepic` and `edituser`. Implementation of the two
commands required an analysis of the pros and cons of the various possible options.

** Jackson Huang implemented the basic classes required for a User Profile.

* *Minor enhancement*: Added price and allergy attribute to Food.

** Justification: These 2 attributes allows HackEat to create a personalised experience for the user. Based on the allergies of the user
and the food, an appropriate food will be ordered. A future enhancement would include taking the budget of the user into account.

* *Code contributed*: [https://github.com/CS2103JAN2018-W10-B3/main/blob/master/collated/functional/tohcheryl.md[Functional code]] [https://github.com/CS2103JAN2018-W10-B3/main/blob/master/collated/test/tohcheryl.md[Test code]]

* *Other contributions*:

** Enhancements to existing features:
*** Wrote additional tests for existing features to increase coverage from 88% to 90% (https://github.com/CS2103JAN2018-W10-B3/main/pull/76[#76])
*** Update User Guide to align with HackEat

** Community:
*** Reported bugs and suggestions for other teams in the class (example: https://github.com/CS2103JAN2018-W13-B3/main/issues/151[#151])

** Tools:
*** Set up Coveralls for the team

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=edituser]

include::../UserGuide.adoc[tag=changepic]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=changepic]

include::../DeveloperGuide.adoc[tag=edituser]
