= Sam Xie - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: AddressBook - Level 4

---

== Overview

AddressBook - Level 4 is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* Optional email and address fields
* Revamped test cases to be Food instead of Persons
* Display price and ratings in UI
* Changed Logo
* Added Ratings field
* Added Order Command
* Implemented server-side REST API for ordering
** Found here: https://github.com/CS2103JAN2018-W10-B3/hackeat-server
* Implemented a Food selection algorithm


== Contributions to the User Guide
include::../UserGuide.adoc[tag=orderfood]

== Contributions to the Developer Guide
include::../DeveloperGuide.adoc[tag=order]

== Future proposals

=== Smarter ordering AI agent
Possibly implement smarter speech with `<Gather>` and `<Redirect>`.

1. `<Gather>` gathers data from user in form of speech, and posts to the url /create/:id/response at the REST API.
2. API parses the information and generates new XML data specific to the response at /order/:id/response.
3. `<Redirect>` redirects chat flow to /order/:id/response and retrieves XML data and confirms, repeats or declines the order.

API Links:

* `<Gather>`
** https://www.twilio.com/docs/voice/twiml/gather
* `<Redirect>`
** https://www.twilio.com/docs/voice/twiml/redirect
